name: vBuckets
version: 0.1.1-BETA
main: com.nbdsteve.vbuckets.vBuckets
api-version: 1.13
commands:
  vb:
    usage: /<command>
    description: Type '/vb help' for command help.
  gen:
    usage: /<command>
    description: Type '/gen help' for command help.
