name: vBuckets
version: 0.2.3
main: dev.nuer.vbuckets.vBuckets
author: Nuer
api-version: 1.13
commands:
  vb:
    usage: /<command>
    description: Type '/vb help' for command help.
  gen:
    usage: /<command>
    description: Type '/gen help' for command help.
